#!/bin/sh
# postrm script for connectd
# updated 06/17/2020

TMP_DIR=/tmp

# clearCrontab removes the command to run connectd_start_all at reboot
clearCrontab()
{
    crontab -l | grep -v connectd_start_all | cat > $TMP_DIR/.crontmp
    crontab $TMP_DIR/.crontmp
}


# clean up specific folders under /etc
cleanFolder()
{
folder=$1
# remove configuration files and folders
    if [ -d /etc/connectd/"$folder" ]; then
        for file in /etc/connectd/"$folder"/*.conf ; do
            rm -f $file
        done
        rmdir /etc/connectd/"$folder"
    fi
    # handle possible backup folders created if there is an auto reg clone.
    if [ -d /etc/connectd/"$folder".prev ]; then
        for file in /etc/connectd/"$folder".prev/*.conf ; do
            rm -f $file
        done
        rmdir /etc/connectd/"$folder".prev
    fi
}


# clearServices stops and disables the connectd & connectd_schannel services
clearServices()
{
   if [ "$(systemctl is-active connectd.service)" = "active" ]; then
      systemctl stop connectd.service
      systemctl disable connectd.service
   fi
   if [ "$(systemctl is-active connectd_schannel.service)" = "active" ]; then
      systemctl stop connectd_schannel.service
      systemctl disable connectd_schannel.service
   fi
}

set -e
logger "connectd installer postrm state $1"
case "$1" in
  purge)
# remove global startup file
    if [ -f /usr/bin/connectd_start_all ]; then
      rm -f /usr/bin/connectd_start_all
    fi
# remove startup scripts created by interactive installer	
    for file in /usr/bin/Connectd* ; do
      rm -f $file
    done
# remove configuration files and folders
    cleanFolder services
    cleanFolder dfiles
    cleanFolder pfiles
    cleanFolder active
    cleanFolder available
    cleanFolder ""
# remove PID files
    for file in /var/run/connectd*.pid ; do
      rm -f $file
    done
# remove installation template files
    if [ -d /usr/share/connectd ]; then
      rm -r /usr/share/connectd
    fi
# remove crontab entry
    clearCrontab
# remove services
    clearServices
    echo
    echo "If you ran ‘sudo dpkg --purge connectd’ on your device without first"
    echo "deleting your remote.it services on that device using connectd_installer,"
    echo "your remote.it account may still believe your device is present but just"
    echo "not responding. If this happens, you can remove the device from your"
    echo "remote.it account using the remote.it website."
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
# remove crontab entry
    clearCrontab
    if [ -d /usr/share/connectd ]; then
      rm -r /usr/share/connectd
    fi
  ;;

  upgrade)
    echo "postrm called with upgrade" > /dev/null
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0
