#!/bin/sh
# postinst script for connectd
# https://remote.it

set -e

logger "connectd installer postinst $1"
 
case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|abort-remove|disappear)
    ;;

    configure|upgrade)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac
echo
echo "================================================================================"
echo "Run \"sudo connectd_installer\" to interactively install remote.it Services on this device."
echo
echo "See https://support.remote.it/hc/en-us/sections/360010786372-Using-the-connectd-package"
echo "for more information."
echo
echo "================================================================================"
