#!/bin/sh

# connectd_stop, stops all running connectd services

BASEDIR=/Users/danawoodman/code/remote.it/installer/connectd
. "$BASEDIR"/usr/bin/connectd_options

for f in "$BIN_DIR"/Connectd*; do
	$f stop
done
"$BIN_DIR"/connectd_schannel stop
