version: 2.1
executors:
  ubuntu:
    docker:
      - image: circleci/node:11.8.0
workflows:
  version: 2
  all:
    jobs:
      - build
jobs:
  build:
    executor: ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: ~/installer
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: apt update
          command: sudo apt-get update
      - run:
          name: Install lintian
          command: sudo apt-get install lintian
      - run:
          name: Install uuid
          command: sudo apt-get install uuid
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Download assets
          command: npm run download-assets
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Build binaries
          command: npm run build
      - store_artifacts:
          path: ~/project/build
